# Generated by Django 4.2.23 on 2025-08-26 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('access_id', models.AutoField(db_column='ACCESS_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'access',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('a_id', models.AutoField(db_column='A_ID', primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='CONTENT')),
                ('time', models.DateTimeField(db_column='TIME')),
                ('t_id', models.IntegerField(db_column='T_ID')),
            ],
            options={
                'db_table': 'announcement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('c_id', models.AutoField(db_column='C_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=20)),
                ('c_code', models.CharField(db_column='C_CODE', max_length=6)),
                ('credits', models.IntegerField(db_column='CREDITS')),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enroll_id', models.AutoField(db_column='ENROLL_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'enrollment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('f_id', models.AutoField(db_column='F_ID', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='DESCRIPTION')),
                ('date', models.DateField(db_column='DATE')),
                ('s_id', models.IntegerField(db_column='S_ID')),
            ],
            options={
                'db_table': 'form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gradesheet',
            fields=[
                ('g_id', models.AutoField(db_column='G_ID', primary_key=True, serialize=False)),
                ('grade', models.TextField(db_column='GRADE')),
            ],
            options={
                'db_table': 'gradesheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('m_id', models.AutoField(db_column='M_ID', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='TITLE')),
                ('type', models.CharField(db_column='TYPE', max_length=9)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('url', models.TextField(db_column='URL')),
            ],
            options={
                'db_table': 'materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('receive_id', models.AutoField(db_column='RECEIVE_ID', primary_key=True, serialize=False)),
                ('s_id', models.IntegerField(db_column='S_ID')),
            ],
            options={
                'db_table': 'receive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sec_id', models.AutoField(db_column='SEC_ID', primary_key=True, serialize=False)),
                ('number', models.IntegerField(db_column='NUMBER')),
                ('room', models.CharField(db_column='ROOM', max_length=10)),
                ('time', models.DateTimeField(db_column='TIME')),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('up_id', models.AutoField(db_column='UP_ID', primary_key=True, serialize=False)),
                ('s_id', models.IntegerField(db_column='S_ID')),
            ],
            options={
                'db_table': 'upload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('view_id', models.AutoField(db_column='VIEW_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('visi_id', models.AutoField(db_column='VISI_ID', primary_key=True, serialize=False)),
                ('t_id', models.IntegerField(db_column='T_ID')),
                ('s_id', models.IntegerField(db_column='S_ID')),
            ],
            options={
                'db_table': 'visibility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'consultation',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(db_column='U_ID', primary_key=True, serialize=False)),
                ('fname', models.CharField(db_column='FNAME', max_length=20)),
                ('mname', models.CharField(blank=True, db_column='MNAME', max_length=20, null=True)),
                ('lname', models.CharField(db_column='LNAME', max_length=20)),
                ('password', models.TextField(db_column='PASSWORD')),
                ('dept', models.CharField(db_column='DEPT', max_length=3)),
                ('type', models.IntegerField(db_column='TYPE')),
                ('s_id', models.IntegerField(blank=True, db_column='S_ID', null=True)),
                ('gsuite', models.TextField(blank=True, db_column='GSUITE', null=True)),
                ('t_id', models.IntegerField(blank=True, db_column='T_ID', null=True)),
                ('gmail', models.TextField(blank=True, db_column='GMAIL', null=True)),
                ('designation', models.CharField(blank=True, db_column='DESIGNATION', max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.consultation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'consultation_message',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_consultations', to='core.users'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_consultations', to='core.users'),
        ),
    ]
